TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "cuff", "cuff any player")
TriggerEvent("chat:addSuggestion", "carry", "carry\'s anyone")
TriggerEvent("chat:addSuggestion", "Drag", "Drag any player")
TriggerEvent("chat:addSuggestion", "dv", "delete any vehicles")
TriggerEvent("chat:addSuggestion", "hu", "raise both hands")
TriggerEvent("chat:addSuggestion", "911", "call\'s dispatch")
TriggerEvent("chat:addSuggestion", "me", "perfroms actions")
TriggerEvent("chat:addSuggestion", "ooc", "Speak out of character")
TriggerEvent("chat:addSuggestion", "looc", "speal for locals")
TriggerEvent("chat:addSuggestion", "run", "runs palte of vehicle")
TriggerEvent("chat:addSuggestion", "211", "non-emergency line")
TriggerEvent("chat:addSuggestion", "311", "request tow")
TriggerEvent("chat:addSuggestion", "Pdalert", "Notifys everyone from cops")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")
TriggerEvent("chat:addSuggestion", "", "")