AddEventHandler("Mackenzie_Rich:Jail", function()
    RegisterNUICallback("Submit", function()
          SendNUIMessage({type = "", visible = true, SetNuiFocus(true, true)})
      end)
        RegisterNUICallback("Trash", function()
          SendNUIMessage({type = "", visible = true, SetNuiFocus(false, false)})
      end)
end)

RegisterNUICallback("Submit", function()
    SendNUIMessage({type = "", visible = true, SetNuiFocus(true, true)})
  end)
RegisterNUICallback("Trash", function()
    SendNUIMessage({type = "", visible = true, SetNuiFocus(false, false)})
  end)
