
let FirstTitle = "Crimes Against a person"
let SimpleAssault = ""
let AssualtWithWeapon = ""
let AssualtOnPoliceOfficer = ""
let AggravatedAssult = ""
let AttemptedMurder = ""
let Mansulter = ""
let Murder = ""
let kidnapingwithunlawfulconfinement = ""
let Toryure = ""

let SecondTitle = "Criminal Property & Criminal Profiteering"
let Arson = ""
let Tresspacsing = ""
let Burblary = ""
let PossessionofBreakinInstrument = ""
let Robery = ""
let Theft = ""
let Theftover500 = ""
let Extortion = ""
let Forgery = ""
let Fraud = ""
let Mischief = ""

let FourTitle = "Criminal Against Public Justice"
let Bribery = ""
let FaiureToPayFine = ""
let ContemptOfCourt = ""
let SuboenaViolation = ""
let ObstructionOfJustice = ""
let ObstructionOfJusticeGoverment = ""
let Falsecomplaint = ""
let Perjury = ""
let ObstructionOfPeaceOfficer =""
let ReasistingAPeaceOfficer = ""
let EscapeFromCustody = ""
let HumanTrafficking = ""
let FabricatingEvidence = ""
let BreachOfProbation = ""
let VoterFraud = ""
let CorruptionOfPublicDuty = ""
let CorruptionOfPublicOfficer = ""

let FifthTitle = "crimes Against a Public Peace"
let DisturbingPeace = ""
let Rioting = ""
let Hatecrime = ""

let SixthTitle = "Crimes Against Public Health and services/Safety"
let PossessionOfControlledSubtance = ""
let PossessionOfControlledLiqour = ""
let Terrosim = ""

let EighthTitle = "Vehicular Offense"
let 